# Generated by Django 3.0.5 on 2020-12-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark1', models.CharField(max_length=30)),
                ('mark2', models.CharField(max_length=30)),
                ('mark3', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=30)),
            ],
        ),
    ]
